### ISSUE TITLE
debian12下执行报错

### ISSUE THREAD

**Issue by vmlive** [jkoor/Alist-Media-Rename#15]
root@Debian12:~# python3 --version
Python 3.11.2
root@Debian12:~# python3 main.py -d xunlei/Tvshows
/usr/local/lib/python3.11/dist-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
Traceback (most recent call last):
  File "/root/main.py", line 3, in <module>
    from AlistMediaRename import Amr
  File "/usr/local/lib/python3.11/dist-packages/AlistMediaRename/__init__.py", line 1, in <module>
    from .api import AlistApi, TMDBApi
  File "/usr/local/lib/python3.11/dist-packages/AlistMediaRename/api.py", line 3, in <module>
    from .utils import PrintMessage
  File "/usr/local/lib/python3.11/dist-packages/AlistMediaRename/utils.py", line 511
    f"{PrintMessage.ColorStr.yellow("文件夹重命名")}:\n {folder_path.split('/')[-2]} -> {renamed_folder_title}"
                                     ^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '('

为何会报语法错误呢？

**Comment by vmlive** [comment]
查到原因了，是引号嵌套导致的问题，涉及utils.py、config.py这两个文件

root@Debian12:~# python3 main.py 出走 -d /xunlei/Tvshows/bbb

[✓] 配置文件加载路径: ./config.json
[✓] 主页: http://127.0.0.1:5244
[✓] 关键词: 出走
 开播时间        序 号      剧 名
----------       -----      ----------------
2010-09-01         0        走进走出
2007-01-23         1        出走五昼夜
2019-10-07         2        出走澳洲
2022-02-03         3        欧拉走出去
2021-09-23         4        离家出走
2016-10-28         5        公园男孩：走出公园的欧洲之旅
2022-02-08         6        走出荣耀—奥运篇
2023-09-13         7        比走出大山更重要的事
                   8        The Shussou - Katte ni ◯◯ Grand Prix
1997-01-01         9        走出凯旋门
2023-10-18         10       走出茶马古道
2024-07-15         11       出走半生缘来是你
2022-04-09         12       我的解放日志
2020-03-26         13       离经叛道
2018-09-04         14       旅行癖
2016-10-09         15       打破常规的警察署长

查询到以上结果，请输入对应[序号], 输入[n]退出   n

**Comment by jkoor** [comment]
> 查到原因了，是引号嵌套导致的问题，涉及utils.py、config.py这两个文件
> 
> root@Debian12:~# python3 main.py 出走 -d /xunlei/Tvshows/bbb
> 
> [✓] 配置文件加载路径: ./config.json
> [✓] 主页: http://127.0.0.1:5244
> [✓] 关键词: 出走
>  开播时间        序 号      剧 名
> ----------       -----      ----------------
> 2010-09-01         0        走进走出
> 2007-01-23         1        出走五昼夜
> 2019-10-07         2        出走澳洲
> 2022-02-03         3        欧拉走出去
> 2021-09-23         4        离家出走
> 2016-10-28         5        公园男孩：走出公园的欧洲之旅
> 2022-02-08         6        走出荣耀—奥运篇
> 2023-09-13         7        比走出大山更重要的事
>                    8        The Shussou - Katte ni ◯◯ Grand Prix
> 1997-01-01         9        走出凯旋门
> 2023-10-18         10       走出茶马古道
> 2024-07-15         11       出走半生缘来是你
> 2022-04-09         12       我的解放日志
> 2020-03-26         13       离经叛道
> 2018-09-04         14       旅行癖
> 2016-10-09         15       打破常规的警察署长
> 
> 查询到以上结果，请输入对应[序号], 输入[n]退出   n

我测试一下这个问题

**Comment by jkoor** [comment]
用了一些python312特性，导致312以下运行失败，已经修复了，可以试试。
