### ISSUE TITLE
macOS Sonoma python3.11环境下运行报错

### ISSUE THREAD

**Issue by x6ufeng** [jkoor/Alist-Media-Rename#5]
首次运行未生成配置文件并给出以下报错
Traceback (most recent call last):
  File "/Users/freddie/Alist-Media-Rename/main.py", line 9, in <module>
    from media_name import AlistMediaRename, Config
  File "/Users/freddie/Alist-Media-Rename/media_name.py", line 246
    print(f"{video["original_name"]} -> {video["target_name"]}")
                    ^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '['
![Uploading Screenshot 2024-02-12 at 14.16.36.png…]()

**Comment by jkoor** [comment]
f'字符串重复使用引号是python3.12新增的特性，我给忘了。

已修复这个问题，请尝试使用最新release或重新拉取仓库。

有问题再联系。
